/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigestWeeklyRouteImport } from './routes/digest.weekly'
import { Route as DigestMonthlyRouteImport } from './routes/digest.monthly'

const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestWeeklyRoute = DigestWeeklyRouteImport.update({
  id: '/digest/weekly',
  path: '/digest/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestMonthlyRoute = DigestMonthlyRouteImport.update({
  id: '/digest/monthly',
  path: '/digest/monthly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/companies': typeof CompaniesRoute
  '/internships': typeof InternshipsRoute
  '/digest/monthly': typeof DigestMonthlyRoute
  '/digest/weekly': typeof DigestWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/companies': typeof CompaniesRoute
  '/internships': typeof InternshipsRoute
  '/digest/monthly': typeof DigestMonthlyRoute
  '/digest/weekly': typeof DigestWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/companies': typeof CompaniesRoute
  '/internships': typeof InternshipsRoute
  '/digest/monthly': typeof DigestMonthlyRoute
  '/digest/weekly': typeof DigestWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/companies'
    | '/internships'
    | '/digest/monthly'
    | '/digest/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/companies'
    | '/internships'
    | '/digest/monthly'
    | '/digest/weekly'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/companies'
    | '/internships'
    | '/digest/monthly'
    | '/digest/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  CompaniesRoute: typeof CompaniesRoute
  InternshipsRoute: typeof InternshipsRoute
  DigestMonthlyRoute: typeof DigestMonthlyRoute
  DigestWeeklyRoute: typeof DigestWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/weekly': {
      id: '/digest/weekly'
      path: '/digest/weekly'
      fullPath: '/digest/weekly'
      preLoaderRoute: typeof DigestWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/monthly': {
      id: '/digest/monthly'
      path: '/digest/monthly'
      fullPath: '/digest/monthly'
      preLoaderRoute: typeof DigestMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  CompaniesRoute: CompaniesRoute,
  InternshipsRoute: InternshipsRoute,
  DigestMonthlyRoute: DigestMonthlyRoute,
  DigestWeeklyRoute: DigestWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
